sudo: require
language: cpp
compiler: gcc

before_install:
    - sudo pip install codecov
script:
    - qmake travis_qmake_gcc_cpp98_gcov.pro
    - make
    - ./travis_qmake_gcc_cpp98_gcov
    - sudo chmod u+x get_code_cov
    - sudo ./get_code_cov
    - codecov
after_success:
    - bash <(curl -s https://codecov.io/bash)
